@startuml
class Season {
- String name
- Date startDate
- Date endDate
- ArrayList<Match> matchs
~ <<Create>> Season()
~ <<Create>> Season(String)
~ <<Create>> Season(String,Date,Date)
+ void setName(String)
+ String getName()
+ void setStartDate(Date)
+ Date getStartDate()
+ Date getEndDate()
+ void setEndDate(Date)
+ ArrayList<Match> getMatchsByDate(Date)
+ void addMatch(Match)
+ ArrayList<Match> getMatchs()
+ void setMatchs(ArrayList<Match>)
}
class Team {
- String name
- ArrayList<Player> players
- int goalCounter
~ <<Create>> Team()
~ <<Create>> Team(String)
+ void setName(String)
+ String getName()
+ ArrayList<Player> getPlayers()
+ void setPlayers(ArrayList<Player>)
+ void addPlayer(Player)
+ void removePlayer(Player)
+ int getGoalCounter()
+ void setGoalCounter(int)
+ void incrementGoalCounter()
}
class Main {
+ {static} void main(String[])
}
class Player {
- String name
- Team team
- String position
- int goalCounter
~ <<Create>> Player(String)
+ String getName()
+ void setName(String)
+ String getPosition()
+ void setPosition(String)
+ int getGoalCounter()
- void setGoalCounter(int)
+ void makeGoal()
+ Team getTeam()
+ void setTeam(Team)
+ void incrementGoalCounter()
}
class MatchResult {
- int localTeamScore
- int visitantTeamScore
- Match match
+ <<Create>> MatchResult(Match)
+ int getLocalTeamScore()
+ void setLocalTeamScore(int)
+ int getVisitantTeamScore()
+ void setVisitantTeamScore(int)
+ void incrementVisitantTeamScore()
+ void incrementLocalTeamScore()
+ String generateMarker()
}
class Match {
- Date date
- String location
- Team localTeam
- Team visitantTeam
- MatchResult result
~ <<Create>> Match()
~ <<Create>> Match(String)
~ <<Create>> Match(String,Date)
~ <<Create>> Match(String,Date,Team,Team)
+ String generateMarker()
+ void generatePlayersList()
+ void setLocation(String)
+ Date getDate()
+ void setDate(Date)
+ Team getLocalTeam()
+ void setLocalTeam(Team)
+ Team getVisitantTeam()
+ void setVisitantTeam(Team)
+ boolean isLocalTeam(Team)
+ boolean isVisitantTeam(Team)
+ void makeGoal(Team,Player)
+ void makeLocalGoal(int)
+ void makeVisitantGoal(int)
}
@enduml